----- 1. How many total orders are recorded in the sales table?

SELECT COUNT(*) AS total_orders
FROM sales;

----- 2. List all unique product categories.

SELECT DISTINCT category
FROM products;
SELECT DISTINCT category
FROM products;

----- 3. How many customers are registered in the dataset?

SELECT COUNT(*) AS Total_Customers
FROM customers;


----- 4. List all stores and the cities they are located in.

SELECT
    store_name,
    city
FROM stores;

----- 5. Which products have a cocoa percentage greater than 70%?

SELECT
    product_name,
    cocoa_percent
FROM products
WHERE cocoa_percent > 70;

----- 6. How many products does each brand offer? List brands and their product count.

SELECT
    brand,
    COUNT(*) AS Product_Count
FROM products
GROUP BY brand
ORDER BY Product_Count DESC;

----- 7. Find all sales where a discount was applied (discount > 0).

SELECT
    order_id,
    discount
FROM sales
WHERE discount > 0;

----- 8. What is the total revenue generated across all sales?

SELECT
    SUM(revenue) AS Total_Revenue
FROM sales;

----- 9. What is the total profit made from all orders?

SELECT
    SUM(profit) AS Total_Profit
FROM sales;

----- 10. What is the minimum and maximum profit from a single order?

SELECT
    MIN(profit) AS Minimum_Profit,
    MAX(profit) AS Maximum_Profit
FROM sales;

----- 11. What is the total quantity sold per product category? (Join sales and products)

SELECT
    p.category,
    SUM(s.quantity) AS Total_Quantity_Sold
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY Total_Quantity_Sold DESC;

----- 12. Show the store name, city, and total revenue for each store. (Join sales and stores)

SELECT
    st.store_name,
    st.city,
    SUM(s.revenue) AS Total_Revenue
FROM sales s
JOIN stores st
    ON s.store_id = st.store_id
GROUP BY st.store_name, st.city
ORDER BY Total_Revenue DESC;

----- 13. Which brand generates the highest total profit? (Join sales and products)

SELECT TOP 1
    p.brand,
    SUM(s.profit) AS Total_Profit
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY p.brand
ORDER BY Total_Profit DESC;

----- 14. Which country generates the most total revenue? (Join sales and stores)

SELECT TOP 1
    st.country,
    SUM(s.revenue) AS Total_Revenue
FROM sales s
JOIN stores st
    ON s.store_id = st.store_id
GROUP BY st.country
ORDER BY Total_Revenue DESC;

----- 15. What is the total revenue generated by loyalty members vs non-loyalty members? (Join sales and customers)

SELECT
    CASE
        WHEN c.loyalty_member = 1 THEN 'Loyalty Member'
        ELSE 'Non-Loyalty Member'
    END AS Customer_Type,
    SUM(s.revenue) AS Total_Revenue
FROM sales s
JOIN customers c
    ON s.customer_id = c.customer_id
GROUP BY c.loyalty_member;

----- 16. List the top 5 products by total quantity sold, including the product name and brand.

SELECT TOP 5
    p.product_name,
    p.brand,
    SUM(s.quantity) AS Total_Quantity_Sold
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY p.product_name, p.brand
ORDER BY Total_Quantity_Sold DESC;

----- 17. Which store type (retail, online, etc.) generates the most revenue?

SELECT
    st.store_type,
    SUM(s.revenue) AS Total_Revenue
FROM sales s
JOIN stores st
    ON s.store_id = st.store_id
GROUP BY st.store_type
ORDER BY Total_Revenue DESC;

----- 18. What is the average order revenue for male vs female customers? (Join sales and customers)

SELECT
    c.gender,
    AVG(s.revenue) AS Average_Order_Revenue
FROM sales s
JOIN customers c
    ON s.customer_id = c.customer_id
GROUP BY c.gender;

----- 19. Which city has the highest number of orders placed? (Join sales and stores)

SELECT TOP 5
    st.city,
    COUNT(s.order_id) AS Total_Orders
FROM sales s
JOIN stores st
    ON s.store_id = st.store_id
GROUP BY st.city
ORDER BY Total_Orders DESC;

----- 20.List the products that have a unit price greater than the average unit price across all products. (Use a subquery)

SELECT DISTINCT
    p.product_name,
    s.unit_price
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
WHERE s.unit_price >
(
    SELECT AVG(unit_price)
    FROM sales
)
ORDER BY s.unit_price DESC;